services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redispass
    volumes:
      - cache:/data
    networks:
      - backend

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ecommerce_spring
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - backend

volumes:
  cache:
    name: cache
    driver: local
  data:
    name: data
    driver: local

networks:
  backend:
    name: backend-net
    driver: bridge
