services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass redispass
    volumes:
      - cache:/data
    networks:
      - backend-net

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ecommerce_spring
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend-net

volumes:
  cache:
    driver: local
  data:
    driver: local

networks:
  backend-net:
    driver: bridge
