services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redispass
    volumes:
      - cache:/data
    networks:
      - ecommerce

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ecommerce_spring
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - ecommerce

  backend:
    image: diegopimenta/ecommerce-spring:latest
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=redispass
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - JWT_SECRET_KEY=5be7c41496c7cb2030b84e63a190d47f6e409a5addaf0d449bf77dc1fc0c6f9c
      - JWT_EXPIRATION_TIME=3600000
    depends_on:
      - redis
      - mysqldb
    networks:
      - ecommerce

volumes:
  cache:
    name: cache-vol
    driver: local
  data:
    name: data-vol
    driver: local

networks:
  ecommerce:
    name: ecommerce-net
    driver: bridge
