server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ecommerce-spring
  profiles:
    active: dev
  jpa:
    open-in-view: false
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:redispass}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret-key: ${SECRET_KEY:5be7c41496c7cb2030b84e63a190d47f6e409a5addaf0d449bf77dc1fc0c6f9c}
    expiration-time: ${TOKEN_EXPIRATION:3600000}
