spring:
  datasource:
    url: jdbc:mysql://${HOST:localhost}:${PORT:3306}/ecommerce_spring?useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
