{
	"info": {
		"_postman_id": "5fbd41fd-f793-4caa-92d1-c603783a2ca3",
		"name": "Ecommerce-Spring",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "30036288"
	},
	"item": [
		{
			"name": "Public",
			"item": [
				{
					"name": "Login-Authentication",
					"event": [
						{
							"listen": "test",
							"script": {
								"exec": [
									"if (pm.response.code === 200 && pm.response.json().token) {",
									"    var token = pm.response.json().token;",
									"    pm.environment.set(\"token\", token);",
									"}"
								],
								"type": "text/javascript",
								"packages": {}
							}
						}
					],
					"request": {
						"method": "POST",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"cpf\": \"12345678902\",\n    \"password\": \"password\"\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{api-gateway}}/v1/auth/login",
							"host": [
								"{{api-gateway}}"
							],
							"path": [
								"v1",
								"auth",
								"login"
							]
						}
					},
					"response": []
				},
				{
					"name": "Reset-Password",
					"request": {
						"method": "POST",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"old_password\": \"\",\n    \"new_password\": \"\"\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						}
					},
					"response": []
				}
			]
		},
		{
			"name": "Product-Stock",
			"item": [
				{
					"name": "Create-Product",
					"request": {
						"method": "POST",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"name\": \"Produto teste\",\n    \"quantity\": \"15\",\n    \"unit_price\": \"9.99\",\n    \"category\": \"Surpresa\"\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{api-gateway}}/v1/products",
							"host": [
								"{{api-gateway}}"
							],
							"path": [
								"v1",
								"products"
							]
						}
					},
					"response": []
				},
				{
					"name": "Get-Product-By-Id",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"url": {
							"raw": "{{api-gateway}}/v1/products/1",
							"host": [
								"{{api-gateway}}"
							],
							"path": [
								"v1",
								"products",
								"1"
							]
						}
					},
					"response": []
				},
				{
					"name": "Get-All-Products",
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"url": {
							"raw": "{{api-gateway}}/v1/products",
							"host": [
								"{{api-gateway}}"
							],
							"path": [
								"v1",
								"products"
							]
						}
					},
					"response": []
				},
				{
					"name": "Update-Product-By-Id",
					"request": {
						"method": "PUT",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"name\": \"Novo nome\",\n    \"quantity\": \"50\",\n    \"unit_price\": \"99.99\",\n    \"category\": \"Atualizado recentemente\",\n    \"inactive_status\": \"false\"\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{api-gateway}}/v1/products/1",
							"host": [
								"{{api-gateway}}"
							],
							"path": [
								"v1",
								"products",
								"1"
							]
						}
					},
					"response": []
				},
				{
					"name": "Update-Product-Status-By-Id",
					"request": {
						"method": "PATCH",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"inactive_status\": \"false\"\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{api-gateway}}/v1/products/update-status/1",
							"host": [
								"{{api-gateway}}"
							],
							"path": [
								"v1",
								"products",
								"update-status",
								"1"
							]
						}
					},
					"response": []
				},
				{
					"name": "Delete-Product-By-Id",
					"request": {
						"method": "DELETE",
						"header": [
							{
								"key": "Accept",
								"value": "application/json"
							}
						],
						"url": {
							"raw": "{{api-gateway}}/v1/products/1",
							"host": [
								"{{api-gateway}}"
							],
							"path": [
								"v1",
								"products",
								"1"
							]
						}
					},
					"response": []
				}
			],
			"auth": {
				"type": "bearer",
				"bearer": [
					{
						"key": "token",
						"value": "{{token}}",
						"type": "string"
					}
				]
			},
			"event": [
				{
					"listen": "prerequest",
					"script": {
						"type": "text/javascript",
						"packages": {},
						"exec": [
							""
						]
					}
				},
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"packages": {},
						"exec": [
							""
						]
					}
				}
			]
		}
	]
}